apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-secrets
  labels:
    app: kubernetes-secrets
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-secrets
  template:
    metadata:
      labels:
        app: kubernetes-secrets
    spec:
      serviceAccountName: my-service-account
      securityContext:
        runAsUser: 100
        runAsGroup: 65532
        fsGroup: 65533
      containers:
      - name: kubernetes-secrets
        image: zreigz/kubernetes-secret:v0.1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        args: ["--namespace=mynamespace", "--secret=mysecret"]
